language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_953939f0dd40_key -iv $encrypted_953939f0dd40_iv
 -in src/main/resources/application.properties.enc -out src/main/resources/application.properties
 -d

